=begin
#NationBuilder V2 API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'

# Unit tests for NationbuilderClient::AsyncProcessesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AsyncProcessesApi' do
  before do
    # run before each test
    @api_instance = NationbuilderClient::AsyncProcessesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AsyncProcessesApi' do
    it 'should create an instance of AsyncProcessesApi' do
      expect(@api_instance).to be_instance_of(NationbuilderClient::AsyncProcessesApi)
    end
  end

  # unit tests for show_async_process
  # Show async process with provided token ID
  # Show async process with provided token ID
  # @param id id
  # @param [Hash] opts the optional parameters
  # @return [ShowAsyncProcess200Response]
  describe 'show_async_process test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
