=begin
#NationBuilder V2 API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'

# Unit tests for NationbuilderClient::EventsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'EventsApi' do
  before do
    # run before each test
    @api_instance = NationbuilderClient::EventsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of EventsApi' do
    it 'should create an instance of EventsApi' do
      expect(@api_instance).to be_instance_of(NationbuilderClient::EventsApi)
    end
  end

  # unit tests for create_event
  # Create an event
  # Create events with the provided payload. Events must be created with a page resource, which can be sideposted as shown in the example payload. Events must also have a start_at time.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Comma-delimited list of sideloaded resources to include as part of the response. See guidance [here](/api/v2/docs#overview--paginating-sideloads) about sideloading large numbers of resources and pagination.  Supported sideloads: auto_response_broadcaster, page, point_person, tracking_code 
  # @option opts [String] :fields_events Comma-delimited list of attributes to only return in the response
  # @option opts [EventCreateRequest] :event_create_request 
  # @return [EventShowResponse]
  describe 'create_event test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_event
  # Delete event with provided ID
  # Delete event with provided ID
  # @param id id
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Comma-delimited list of sideloaded resources to include as part of the response. See guidance [here](/api/v2/docs#overview--paginating-sideloads) about sideloading large numbers of resources and pagination.  Supported sideloads: auto_response_broadcaster, page, point_person, tracking_code, rsvps, event_ticket_levels 
  # @option opts [String] :fields_events Comma-delimited list of attributes to only return in the response
  # @return [EmptyMetaResponse]
  describe 'delete_event test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_events
  # List all events in a nation
  # Lists all events within a nation.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Comma-delimited list of sideloaded resources to include as part of the response. See guidance [here](/api/v2/docs#overview--paginating-sideloads) about sideloading large numbers of resources and pagination.  Supported sideloads: auto_response_broadcaster, page, point_person, tracking_code 
  # @option opts [String] :fields_events Comma-delimited list of attributes to only return in the response
  # @option opts [String] :page_number Page number to list (starting at 1)
  # @option opts [String] :page_size Number of results to display per page (default: 20, max: 100, min: 1)
  # @return [EventIndexResponse]
  describe 'list_events test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for show_event
  # Show event with provided ID
  # Show event with provided ID
  # @param id id
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Comma-delimited list of sideloaded resources to include as part of the response. See guidance [here](/api/v2/docs#overview--paginating-sideloads) about sideloading large numbers of resources and pagination.  Supported sideloads: auto_response_broadcaster, page, point_person, tracking_code, rsvps, event_ticket_levels 
  # @option opts [String] :fields_events Comma-delimited list of attributes to only return in the response
  # @return [EventShowResponse]
  describe 'show_event test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_event
  # Update an existing event
  # Updates an existing event
  # @param id id
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Comma-delimited list of sideloaded resources to include as part of the response. See guidance [here](/api/v2/docs#overview--paginating-sideloads) about sideloading large numbers of resources and pagination.  Supported sideloads: auto_response_broadcaster, page, point_person, tracking_code, rsvps, event_ticket_levels 
  # @option opts [String] :fields_events Comma-delimited list of attributes to only return in the response
  # @option opts [EventUpdateRequest] :event_update_request 
  # @return [EventShowResponse]
  describe 'update_event test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
