=begin
#NationBuilder V2 API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'

# Unit tests for NationbuilderClient::MembershipTypesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'MembershipTypesApi' do
  before do
    # run before each test
    @api_instance = NationbuilderClient::MembershipTypesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MembershipTypesApi' do
    it 'should create an instance of MembershipTypesApi' do
      expect(@api_instance).to be_instance_of(NationbuilderClient::MembershipTypesApi)
    end
  end

  # unit tests for create_membership_type
  # Create a membership type
  # Creates a membership type from given data
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Comma-delimited list of sideloaded resources to include as part of the response. See guidance [here](/api/v2/docs#overview--paginating-sideloads) about sideloading large numbers of resources and pagination.  Supported sideloads: page 
  # @option opts [String] :fields_membership_types Comma-delimited list of attributes to only return in the response
  # @option opts [MembershipTypeCreateRequest] :membership_type_create_request 
  # @return [MembershipTypeShowResponse]
  describe 'create_membership_type test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_membership_type
  # Delete membership type with provided ID
  # Delete membership type with provided ID
  # @param id id
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Comma-delimited list of sideloaded resources to include as part of the response. See guidance [here](/api/v2/docs#overview--paginating-sideloads) about sideloading large numbers of resources and pagination.  Supported sideloads: page, memberships 
  # @option opts [String] :fields_membership_types Comma-delimited list of attributes to only return in the response
  # @return [EmptyMetaResponse]
  describe 'delete_membership_type test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_membership_types
  # List all membership types in a nation
  # Lists all membership types
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Comma-delimited list of sideloaded resources to include as part of the response. See guidance [here](/api/v2/docs#overview--paginating-sideloads) about sideloading large numbers of resources and pagination.  Supported sideloads: page 
  # @option opts [String] :fields_membership_types Comma-delimited list of attributes to only return in the response
  # @option opts [String] :page_number Page number to list (starting at 1)
  # @option opts [String] :page_size Number of results to display per page (default: 20, max: 100, min: 1)
  # @return [MembershipTypeIndexResponse]
  describe 'list_membership_types test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for show_membership_type
  # Show membership type with provided ID
  # Show membership type with provided ID
  # @param id id
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Comma-delimited list of sideloaded resources to include as part of the response. See guidance [here](/api/v2/docs#overview--paginating-sideloads) about sideloading large numbers of resources and pagination.  Supported sideloads: page, memberships 
  # @option opts [String] :fields_membership_types Comma-delimited list of attributes to only return in the response
  # @return [MembershipTypeShowResponse]
  describe 'show_membership_type test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_membership_type
  # Update an existing membership type
  # Updates an existing membership type
  # @param id id
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Comma-delimited list of sideloaded resources to include as part of the response. See guidance [here](/api/v2/docs#overview--paginating-sideloads) about sideloading large numbers of resources and pagination.  Supported sideloads: page, memberships 
  # @option opts [String] :fields_membership_types Comma-delimited list of attributes to only return in the response
  # @option opts [MembershipTypeUpdateRequest] :membership_type_update_request 
  # @return [MembershipTypeShowResponse]
  describe 'update_membership_type test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
