=begin
#NationBuilder V2 API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'

# Unit tests for NationbuilderClient::PagesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PagesApi' do
  before do
    # run before each test
    @api_instance = NationbuilderClient::PagesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PagesApi' do
    it 'should create an instance of PagesApi' do
      expect(@api_instance).to be_instance_of(NationbuilderClient::PagesApi)
    end
  end

  # unit tests for create_page
  # Create a page
  # Creates a page from given data
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Comma-delimited list of sideloaded resources to include as part of the response. See guidance [here](/api/v2/docs#overview--paginating-sideloads) about sideloading large numbers of resources and pagination.  Supported sideloads: site 
  # @option opts [String] :fields_pages Comma-delimited list of attributes to only return in the response
  # @option opts [PageCreateRequest] :page_create_request 
  # @return [PageShowResponse]
  describe 'create_page test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_page
  # Delete page with provided ID
  # Delete page with provided ID
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Comma-delimited list of sideloaded resources to include as part of the response. See guidance [here](/api/v2/docs#overview--paginating-sideloads) about sideloading large numbers of resources and pagination.  Supported sideloads: site, membership_types 
  # @option opts [String] :fields_pages Comma-delimited list of attributes to only return in the response
  # @return [EmptyMetaResponse]
  describe 'delete_page test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_pages
  # List all pages in a nation
  # Lists all pages
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Comma-delimited list of sideloaded resources to include as part of the response. See guidance [here](/api/v2/docs#overview--paginating-sideloads) about sideloading large numbers of resources and pagination.  Supported sideloads: site 
  # @option opts [String] :fields_pages Comma-delimited list of attributes to only return in the response
  # @option opts [String] :page_number Page number to list (starting at 1)
  # @option opts [String] :page_size Number of results to display per page (default: 20, max: 100, min: 1)
  # @return [PageIndexResponse]
  describe 'list_pages test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for show_page
  # Show page with provided ID
  # Show page with provided ID 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Comma-delimited list of sideloaded resources to include as part of the response. See guidance [here](/api/v2/docs#overview--paginating-sideloads) about sideloading large numbers of resources and pagination.  Supported sideloads: site, membership_types 
  # @option opts [String] :fields_pages Comma-delimited list of attributes to only return in the response
  # @return [PageShowResponse]
  describe 'show_page test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_page
  # Update an existing page
  # Updates an existing page
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Comma-delimited list of sideloaded resources to include as part of the response. See guidance [here](/api/v2/docs#overview--paginating-sideloads) about sideloading large numbers of resources and pagination.  Supported sideloads: site, membership_types 
  # @option opts [String] :fields_pages Comma-delimited list of attributes to only return in the response
  # @option opts [PageUpdateRequest] :page_update_request 
  # @return [PageShowResponse]
  describe 'update_page test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
