=begin
#NationBuilder V2 API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'

# Unit tests for NationbuilderClient::PathsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PathsApi' do
  before do
    # run before each test
    @api_instance = NationbuilderClient::PathsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PathsApi' do
    it 'should create an instance of PathsApi' do
      expect(@api_instance).to be_instance_of(NationbuilderClient::PathsApi)
    end
  end

  # unit tests for create_path
  # Create a path
  # Creates a path from given data
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Comma-delimited list of sideloaded resources to include as part of the response. See guidance [here](/api/v2/docs#overview--paginating-sideloads) about sideloading large numbers of resources and pagination.  Supported sideloads: default_point_person 
  # @option opts [String] :fields_paths Comma-delimited list of attributes to only return in the response
  # @option opts [PathCreateRequest] :path_create_request 
  # @return [PathShowResponse]
  describe 'create_path test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_path
  # Delete path with provided ID
  # Delete path with provided ID
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Comma-delimited list of sideloaded resources to include as part of the response. See guidance [here](/api/v2/docs#overview--paginating-sideloads) about sideloading large numbers of resources and pagination.  Supported sideloads: path_journeys, path_steps, path_journey_status_changes, default_point_person 
  # @option opts [String] :fields_paths Comma-delimited list of attributes to only return in the response
  # @return [EmptyMetaResponse]
  describe 'delete_path test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_paths
  # List all paths in a nation
  # Lists all paths
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Comma-delimited list of sideloaded resources to include as part of the response. See guidance [here](/api/v2/docs#overview--paginating-sideloads) about sideloading large numbers of resources and pagination.  Supported sideloads: default_point_person 
  # @option opts [String] :fields_paths Comma-delimited list of attributes to only return in the response
  # @option opts [String] :page_number Page number to list (starting at 1)
  # @option opts [String] :page_size Number of results to display per page (default: 20, max: 100, min: 1)
  # @return [PathIndexResponse]
  describe 'list_paths test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for show_path
  # Show path with provided ID
  # Show path with provided ID 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Comma-delimited list of sideloaded resources to include as part of the response. See guidance [here](/api/v2/docs#overview--paginating-sideloads) about sideloading large numbers of resources and pagination.  Supported sideloads: path_journeys, path_steps, path_journey_status_changes, default_point_person 
  # @option opts [String] :fields_paths Comma-delimited list of attributes to only return in the response
  # @return [PathShowResponse]
  describe 'show_path test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_path
  # Update an existing path
  # Updates an existing path
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Comma-delimited list of sideloaded resources to include as part of the response. See guidance [here](/api/v2/docs#overview--paginating-sideloads) about sideloading large numbers of resources and pagination.  Supported sideloads: path_journeys, path_steps, path_journey_status_changes, default_point_person 
  # @option opts [String] :fields_paths Comma-delimited list of attributes to only return in the response
  # @option opts [PathUpdateRequest] :path_update_request 
  # @return [PathShowResponse]
  describe 'update_path test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
