=begin
#NationBuilder V2 API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'

# Unit tests for NationbuilderClient::PetitionSignaturesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PetitionSignaturesApi' do
  before do
    # run before each test
    @api_instance = NationbuilderClient::PetitionSignaturesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PetitionSignaturesApi' do
    it 'should create an instance of PetitionSignaturesApi' do
      expect(@api_instance).to be_instance_of(NationbuilderClient::PetitionSignaturesApi)
    end
  end

  # unit tests for create_petition_signature
  # Create a petition signature
  # Creates a petition signature from given data
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Comma-delimited list of sideloaded resources to include as part of the response. See guidance [here](/api/v2/docs#overview--paginating-sideloads) about sideloading large numbers of resources and pagination.  Supported sideloads: page, petition, recruiter, signup 
  # @option opts [String] :fields_petition_signatures Comma-delimited list of attributes to only return in the response
  # @option opts [PetitionSignatureCreateRequest] :petition_signature_create_request 
  # @return [PetitionSignatureShowResponse]
  describe 'create_petition_signature test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_petition_signature
  # Delete petition signature with provided ID
  # Delete petition signature with provided ID
  # @param id id
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Comma-delimited list of sideloaded resources to include as part of the response. See guidance [here](/api/v2/docs#overview--paginating-sideloads) about sideloading large numbers of resources and pagination.  Supported sideloads: page, petition, recruiter, signup 
  # @option opts [String] :fields_petition_signatures Comma-delimited list of attributes to only return in the response
  # @return [EmptyMetaResponse]
  describe 'delete_petition_signature test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_petition_signatures
  # List all petition signatures in a nation
  # Lists all petition signatures
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Comma-delimited list of sideloaded resources to include as part of the response. See guidance [here](/api/v2/docs#overview--paginating-sideloads) about sideloading large numbers of resources and pagination.  Supported sideloads: page, petition, recruiter, signup 
  # @option opts [String] :fields_petition_signatures Comma-delimited list of attributes to only return in the response
  # @option opts [String] :page_number Page number to list (starting at 1)
  # @option opts [String] :page_size Number of results to display per page (default: 20, max: 100, min: 1)
  # @return [PetitionSignatureIndexResponse]
  describe 'list_petition_signatures test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for show_petition_signature
  # Show petition signature with provided ID
  # Show petition signature with provided ID 
  # @param id id
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Comma-delimited list of sideloaded resources to include as part of the response. See guidance [here](/api/v2/docs#overview--paginating-sideloads) about sideloading large numbers of resources and pagination.  Supported sideloads: page, petition, recruiter, signup 
  # @option opts [String] :fields_petition_signatures Comma-delimited list of attributes to only return in the response
  # @return [PetitionSignatureShowResponse]
  describe 'show_petition_signature test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_petition_signature
  # Update an existing petition signature
  # Updates an existing petition signature
  # @param id id
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Comma-delimited list of sideloaded resources to include as part of the response. See guidance [here](/api/v2/docs#overview--paginating-sideloads) about sideloading large numbers of resources and pagination.  Supported sideloads: page, petition, recruiter, signup 
  # @option opts [String] :fields_petition_signatures Comma-delimited list of attributes to only return in the response
  # @option opts [PetitionSignatureUpdateRequest] :petition_signature_update_request 
  # @return [PetitionSignatureShowResponse]
  describe 'update_petition_signature test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
