=begin
#NationBuilder V2 API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'

# Unit tests for NationbuilderClient::SignupProfilesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SignupProfilesApi' do
  before do
    # run before each test
    @api_instance = NationbuilderClient::SignupProfilesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SignupProfilesApi' do
    it 'should create an instance of SignupProfilesApi' do
      expect(@api_instance).to be_instance_of(NationbuilderClient::SignupProfilesApi)
    end
  end

  # unit tests for create_signup_profile
  # Create a signup profile
  # Creates a signup profile from given data
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Comma-delimited list of sideloaded resources to include as part of the response. See guidance [here](/api/v2/docs#overview--paginating-sideloads) about sideloading large numbers of resources and pagination.  Supported sideloads: signup 
  # @option opts [String] :fields_signup_profiles Comma-delimited list of attributes to only return in the response
  # @option opts [SignupProfileCreateRequest] :signup_profile_create_request 
  # @return [SignupProfileShowResponse]
  describe 'create_signup_profile test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_signup_profile
  # Delete signup profile with provided ID
  # Delete signup_profile with provided ID
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Comma-delimited list of sideloaded resources to include as part of the response. See guidance [here](/api/v2/docs#overview--paginating-sideloads) about sideloading large numbers of resources and pagination.  Supported sideloads: signup 
  # @option opts [String] :fields_signup_profiles Comma-delimited list of attributes to only return in the response
  # @return [EmptyMetaResponse]
  describe 'delete_signup_profile test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_signup_profiles
  # List all signup profiles in a nation
  # Lists all signup profiles
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Comma-delimited list of sideloaded resources to include as part of the response. See guidance [here](/api/v2/docs#overview--paginating-sideloads) about sideloading large numbers of resources and pagination.  Supported sideloads: signup 
  # @option opts [String] :fields_signup_profiles Comma-delimited list of attributes to only return in the response
  # @option opts [String] :page_number Page number to list (starting at 1)
  # @option opts [String] :page_size Number of results to display per page (default: 20, max: 100, min: 1)
  # @return [SignupProfileIndexResponse]
  describe 'list_signup_profiles test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for show_signup_profile
  # Show signup profile with provided ID
  # Show signup profile with provided ID 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Comma-delimited list of sideloaded resources to include as part of the response. See guidance [here](/api/v2/docs#overview--paginating-sideloads) about sideloading large numbers of resources and pagination.  Supported sideloads: signup 
  # @option opts [String] :fields_signup_profiles Comma-delimited list of attributes to only return in the response
  # @return [SignupProfileShowResponse]
  describe 'show_signup_profile test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_signup_profile
  # Update an existing signup profile
  # Updates an existing signup profile
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Comma-delimited list of sideloaded resources to include as part of the response. See guidance [here](/api/v2/docs#overview--paginating-sideloads) about sideloading large numbers of resources and pagination.  Supported sideloads: signup 
  # @option opts [String] :fields_signup_profiles Comma-delimited list of attributes to only return in the response
  # @option opts [SignupProfileUpdateRequest] :signup_profile_update_request 
  # @return [SignupProfileShowResponse]
  describe 'update_signup_profile test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
