=begin
#NationBuilder V2 API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'

# Unit tests for NationbuilderClient::SurveysApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SurveysApi' do
  before do
    # run before each test
    @api_instance = NationbuilderClient::SurveysApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SurveysApi' do
    it 'should create an instance of SurveysApi' do
      expect(@api_instance).to be_instance_of(NationbuilderClient::SurveysApi)
    end
  end

  # unit tests for create_survey
  # Create a survey
  # Creates a survey from given data
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Comma-delimited list of sideloaded resources to include as part of the response. See guidance [here](/api/v2/docs#overview--paginating-sideloads) about sideloading large numbers of resources and pagination.  Supported sideloads: (none) 
  # @option opts [String] :fields_surveys Comma-delimited list of attributes to only return in the response
  # @option opts [SurveyCreateRequest] :survey_create_request 
  # @return [SurveyShowResponse]
  describe 'create_survey test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_survey
  # Delete survey with provided ID
  # Delete survey with provided ID
  # @param id id
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Comma-delimited list of sideloaded resources to include as part of the response. See guidance [here](/api/v2/docs#overview--paginating-sideloads) about sideloading large numbers of resources and pagination.  Supported sideloads: survey_questions 
  # @option opts [String] :fields_surveys Comma-delimited list of attributes to only return in the response
  # @return [EmptyMetaResponse]
  describe 'delete_survey test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_surveys
  # List all surveys in a nation
  # Lists all surveys
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Comma-delimited list of sideloaded resources to include as part of the response. See guidance [here](/api/v2/docs#overview--paginating-sideloads) about sideloading large numbers of resources and pagination.  Supported sideloads: (none) 
  # @option opts [String] :fields_surveys Comma-delimited list of attributes to only return in the response
  # @option opts [String] :page_number Page number to list (starting at 1)
  # @option opts [String] :page_size Number of results to display per page (default: 20, max: 100, min: 1)
  # @return [SurveyIndexResponse]
  describe 'list_surveys test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for show_survey
  # Show survey with provided ID
  # Show survey with provided ID
  # @param id id
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Comma-delimited list of sideloaded resources to include as part of the response. See guidance [here](/api/v2/docs#overview--paginating-sideloads) about sideloading large numbers of resources and pagination.  Supported sideloads: survey_questions 
  # @option opts [String] :fields_surveys Comma-delimited list of attributes to only return in the response
  # @return [SurveyShowResponse]
  describe 'show_survey test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_survey
  # Update an existing survey
  # Updates an existing survey
  # @param id id
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Comma-delimited list of sideloaded resources to include as part of the response. See guidance [here](/api/v2/docs#overview--paginating-sideloads) about sideloading large numbers of resources and pagination.  Supported sideloads: survey_questions 
  # @option opts [String] :fields_surveys Comma-delimited list of attributes to only return in the response
  # @option opts [SurveyUpdateRequest] :survey_update_request 
  # @return [SurveyShowResponse]
  describe 'update_survey test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
