=begin
#NationBuilder V2 API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for NationbuilderClient::ImportIndexResponseLinksLinks
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe NationbuilderClient::ImportIndexResponseLinksLinks do
  let(:instance) { NationbuilderClient::ImportIndexResponseLinksLinks.new }

  describe 'test an instance of ImportIndexResponseLinksLinks' do
    it 'should create an instance of ImportIndexResponseLinksLinks' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(NationbuilderClient::ImportIndexResponseLinksLinks)
    end
  end

  describe 'test attribute "_self"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "prev"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "_next"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
