=begin
#NationBuilder V2 API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for NationbuilderClient::VoterIndexResponseLinks
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe NationbuilderClient::VoterIndexResponseLinks do
  let(:instance) { NationbuilderClient::VoterIndexResponseLinks.new }

  describe 'test an instance of VoterIndexResponseLinks' do
    it 'should create an instance of VoterIndexResponseLinks' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(NationbuilderClient::VoterIndexResponseLinks)
    end
  end

  describe 'test attribute "links"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
