# #NationBuilder V2 API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 2.0
#
# Generated by: https://openapi-generator.tech
# Generator version: 7.9.0
#

require "cgi"

module NationbuilderClient
  class PathJourneysApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end

    # Abandon path journey with provided ID
    # Abandon path journey with provided ID
    # @param id [String]
    # @param [Hash] opts the optional parameters
    # @option opts [String] :path_journey_status_change_id ID for abandonment reason
    # @option opts [String] :include Comma-delimited list of sideloaded resources to include as part of the response. See guidance [here](/api/v2/docs#overview--paginating-sideloads) about sideloading large numbers of resources and pagination.  Supported sideloads: signup, path, point_person, current_step_point_person, path_journey_status_change, current_step, path_histories
    # @option opts [String] :fields_path_journeys Comma-delimited list of attributes to only return in the response
    # @return [PathJourneyShowResponse]
    def abandon_path_journey(id, opts = {})
      data, _status_code, _headers = abandon_path_journey_with_http_info(id, opts)
      data
    end

    # Abandon path journey with provided ID
    # Abandon path journey with provided ID
    # @param id [String]
    # @param [Hash] opts the optional parameters
    # @option opts [String] :path_journey_status_change_id ID for abandonment reason
    # @option opts [String] :include Comma-delimited list of sideloaded resources to include as part of the response. See guidance [here](/api/v2/docs#overview--paginating-sideloads) about sideloading large numbers of resources and pagination.  Supported sideloads: signup, path, point_person, current_step_point_person, path_journey_status_change, current_step, path_histories
    # @option opts [String] :fields_path_journeys Comma-delimited list of attributes to only return in the response
    # @return [Array<(PathJourneyShowResponse, Integer, Hash)>] PathJourneyShowResponse data, response status code and response headers
    def abandon_path_journey_with_http_info(id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: PathJourneysApi.abandon_path_journey ..."
      end
      # verify the required parameter 'id' is set
      if @api_client.config.client_side_validation && id.nil?
        fail ArgumentError, "Missing the required parameter 'id' when calling PathJourneysApi.abandon_path_journey"
      end
      # resource path
      local_var_path = "/api/v2/path_journeys/{id}/abandon".sub("{" + "id" + "}", CGI.escape(id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:path_journey_status_change_id] = opts[:path_journey_status_change_id] if !opts[:path_journey_status_change_id].nil?
      query_params[:include] = opts[:include] if !opts[:include].nil?
      query_params[:"fields[path_journeys]"] = opts[:fields_path_journeys] if !opts[:fields_path_journeys].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"]) unless header_params["Accept"]

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || "PathJourneyShowResponse"

      # auth_names
      auth_names = opts[:debug_auth_names] || ["BearerAuth"]

      new_options = opts.merge(
        operation: :"PathJourneysApi.abandon_path_journey",
        header_params: header_params,
        query_params: query_params,
        form_params: form_params,
        body: post_body,
        auth_names: auth_names,
        return_type: return_type
      )

      data, status_code, headers = @api_client.call_api(:PATCH, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: PathJourneysApi#abandon_path_journey\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      [data, status_code, headers]
    end

    # Complete path journey with provided ID
    # Complete path journey with provided ID
    # @param id [String]
    # @param [Hash] opts the optional parameters
    # @option opts [String] :path_journey_status_change_id ID for completion reason
    # @option opts [String] :include Comma-delimited list of sideloaded resources to include as part of the response. See guidance [here](/api/v2/docs#overview--paginating-sideloads) about sideloading large numbers of resources and pagination.  Supported sideloads: signup, path, point_person, current_step_point_person, path_journey_status_change, current_step, path_histories
    # @option opts [String] :fields_path_journeys Comma-delimited list of attributes to only return in the response
    # @return [PathJourneyShowResponse]
    def complete_path_journey(id, opts = {})
      data, _status_code, _headers = complete_path_journey_with_http_info(id, opts)
      data
    end

    # Complete path journey with provided ID
    # Complete path journey with provided ID
    # @param id [String]
    # @param [Hash] opts the optional parameters
    # @option opts [String] :path_journey_status_change_id ID for completion reason
    # @option opts [String] :include Comma-delimited list of sideloaded resources to include as part of the response. See guidance [here](/api/v2/docs#overview--paginating-sideloads) about sideloading large numbers of resources and pagination.  Supported sideloads: signup, path, point_person, current_step_point_person, path_journey_status_change, current_step, path_histories
    # @option opts [String] :fields_path_journeys Comma-delimited list of attributes to only return in the response
    # @return [Array<(PathJourneyShowResponse, Integer, Hash)>] PathJourneyShowResponse data, response status code and response headers
    def complete_path_journey_with_http_info(id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: PathJourneysApi.complete_path_journey ..."
      end
      # verify the required parameter 'id' is set
      if @api_client.config.client_side_validation && id.nil?
        fail ArgumentError, "Missing the required parameter 'id' when calling PathJourneysApi.complete_path_journey"
      end
      # resource path
      local_var_path = "/api/v2/path_journeys/{id}/complete".sub("{" + "id" + "}", CGI.escape(id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:path_journey_status_change_id] = opts[:path_journey_status_change_id] if !opts[:path_journey_status_change_id].nil?
      query_params[:include] = opts[:include] if !opts[:include].nil?
      query_params[:"fields[path_journeys]"] = opts[:fields_path_journeys] if !opts[:fields_path_journeys].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"]) unless header_params["Accept"]

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || "PathJourneyShowResponse"

      # auth_names
      auth_names = opts[:debug_auth_names] || ["BearerAuth"]

      new_options = opts.merge(
        operation: :"PathJourneysApi.complete_path_journey",
        header_params: header_params,
        query_params: query_params,
        form_params: form_params,
        body: post_body,
        auth_names: auth_names,
        return_type: return_type
      )

      data, status_code, headers = @api_client.call_api(:PATCH, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: PathJourneysApi#complete_path_journey\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      [data, status_code, headers]
    end

    # Create a path journey
    # Creates a path journey from given data
    # @param [Hash] opts the optional parameters
    # @option opts [String] :include Comma-delimited list of sideloaded resources to include as part of the response. See guidance [here](/api/v2/docs#overview--paginating-sideloads) about sideloading large numbers of resources and pagination.  Supported sideloads: signup, path, point_person, current_step_point_person, path_journey_status_change, current_step
    # @option opts [String] :fields_path_journeys Comma-delimited list of attributes to only return in the response
    # @option opts [PathJourneyCreateRequest] :path_journey_create_request
    # @return [PathJourneyShowResponse]
    def create_path_journey(opts = {})
      data, _status_code, _headers = create_path_journey_with_http_info(opts)
      data
    end

    # Create a path journey
    # Creates a path journey from given data
    # @param [Hash] opts the optional parameters
    # @option opts [String] :include Comma-delimited list of sideloaded resources to include as part of the response. See guidance [here](/api/v2/docs#overview--paginating-sideloads) about sideloading large numbers of resources and pagination.  Supported sideloads: signup, path, point_person, current_step_point_person, path_journey_status_change, current_step
    # @option opts [String] :fields_path_journeys Comma-delimited list of attributes to only return in the response
    # @option opts [PathJourneyCreateRequest] :path_journey_create_request
    # @return [Array<(PathJourneyShowResponse, Integer, Hash)>] PathJourneyShowResponse data, response status code and response headers
    def create_path_journey_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: PathJourneysApi.create_path_journey ..."
      end
      # resource path
      local_var_path = "/api/v2/path_journeys"

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:include] = opts[:include] if !opts[:include].nil?
      query_params[:"fields[path_journeys]"] = opts[:fields_path_journeys] if !opts[:fields_path_journeys].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"]) unless header_params["Accept"]
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(["application/json"])
      if !content_type.nil?
          header_params["Content-Type"] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(opts[:path_journey_create_request])

      # return_type
      return_type = opts[:debug_return_type] || "PathJourneyShowResponse"

      # auth_names
      auth_names = opts[:debug_auth_names] || ["BearerAuth"]

      new_options = opts.merge(
        operation: :"PathJourneysApi.create_path_journey",
        header_params: header_params,
        query_params: query_params,
        form_params: form_params,
        body: post_body,
        auth_names: auth_names,
        return_type: return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: PathJourneysApi#create_path_journey\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      [data, status_code, headers]
    end

    # List all path journeys in a nation
    # Lists all path journeys
    # @param [Hash] opts the optional parameters
    # @option opts [String] :include Comma-delimited list of sideloaded resources to include as part of the response. See guidance [here](/api/v2/docs#overview--paginating-sideloads) about sideloading large numbers of resources and pagination.  Supported sideloads: signup, path, point_person, current_step_point_person, path_journey_status_change, current_step
    # @option opts [String] :fields_path_journeys Comma-delimited list of attributes to only return in the response
    # @option opts [String] :page_number Page number to list (starting at 1)
    # @option opts [String] :page_size Number of results to display per page (default: 20, max: 100, min: 1)
    # @return [PathJourneyIndexResponse]
    def list_path_journeys(opts = {})
      data, _status_code, _headers = list_path_journeys_with_http_info(opts)
      data
    end

    # List all path journeys in a nation
    # Lists all path journeys
    # @param [Hash] opts the optional parameters
    # @option opts [String] :include Comma-delimited list of sideloaded resources to include as part of the response. See guidance [here](/api/v2/docs#overview--paginating-sideloads) about sideloading large numbers of resources and pagination.  Supported sideloads: signup, path, point_person, current_step_point_person, path_journey_status_change, current_step
    # @option opts [String] :fields_path_journeys Comma-delimited list of attributes to only return in the response
    # @option opts [String] :page_number Page number to list (starting at 1)
    # @option opts [String] :page_size Number of results to display per page (default: 20, max: 100, min: 1)
    # @return [Array<(PathJourneyIndexResponse, Integer, Hash)>] PathJourneyIndexResponse data, response status code and response headers
    def list_path_journeys_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: PathJourneysApi.list_path_journeys ..."
      end
      # resource path
      local_var_path = "/api/v2/path_journeys"

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:include] = opts[:include] if !opts[:include].nil?
      query_params[:"fields[path_journeys]"] = opts[:fields_path_journeys] if !opts[:fields_path_journeys].nil?
      query_params[:"page[number]"] = opts[:page_number] if !opts[:page_number].nil?
      query_params[:"page[size]"] = opts[:page_size] if !opts[:page_size].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"]) unless header_params["Accept"]

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || "PathJourneyIndexResponse"

      # auth_names
      auth_names = opts[:debug_auth_names] || ["BearerAuth"]

      new_options = opts.merge(
        operation: :"PathJourneysApi.list_path_journeys",
        header_params: header_params,
        query_params: query_params,
        form_params: form_params,
        body: post_body,
        auth_names: auth_names,
        return_type: return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: PathJourneysApi#list_path_journeys\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      [data, status_code, headers]
    end

    # Reactivate path journey with provided ID
    # Reactivate path journey with provided ID
    # @param id [String]
    # @param [Hash] opts the optional parameters
    # @option opts [String] :include Comma-delimited list of sideloaded resources to include as part of the response. See guidance [here](/api/v2/docs#overview--paginating-sideloads) about sideloading large numbers of resources and pagination.  Supported sideloads: signup, path, point_person, current_step_point_person, path_journey_status_change, current_step, path_histories
    # @option opts [String] :fields_path_journeys Comma-delimited list of attributes to only return in the response
    # @return [PathJourneyShowResponse]
    def reactivate_path_journey(id, opts = {})
      data, _status_code, _headers = reactivate_path_journey_with_http_info(id, opts)
      data
    end

    # Reactivate path journey with provided ID
    # Reactivate path journey with provided ID
    # @param id [String]
    # @param [Hash] opts the optional parameters
    # @option opts [String] :include Comma-delimited list of sideloaded resources to include as part of the response. See guidance [here](/api/v2/docs#overview--paginating-sideloads) about sideloading large numbers of resources and pagination.  Supported sideloads: signup, path, point_person, current_step_point_person, path_journey_status_change, current_step, path_histories
    # @option opts [String] :fields_path_journeys Comma-delimited list of attributes to only return in the response
    # @return [Array<(PathJourneyShowResponse, Integer, Hash)>] PathJourneyShowResponse data, response status code and response headers
    def reactivate_path_journey_with_http_info(id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: PathJourneysApi.reactivate_path_journey ..."
      end
      # verify the required parameter 'id' is set
      if @api_client.config.client_side_validation && id.nil?
        fail ArgumentError, "Missing the required parameter 'id' when calling PathJourneysApi.reactivate_path_journey"
      end
      # resource path
      local_var_path = "/api/v2/path_journeys/{id}/reactivate".sub("{" + "id" + "}", CGI.escape(id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:include] = opts[:include] if !opts[:include].nil?
      query_params[:"fields[path_journeys]"] = opts[:fields_path_journeys] if !opts[:fields_path_journeys].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"]) unless header_params["Accept"]

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || "PathJourneyShowResponse"

      # auth_names
      auth_names = opts[:debug_auth_names] || ["BearerAuth"]

      new_options = opts.merge(
        operation: :"PathJourneysApi.reactivate_path_journey",
        header_params: header_params,
        query_params: query_params,
        form_params: form_params,
        body: post_body,
        auth_names: auth_names,
        return_type: return_type
      )

      data, status_code, headers = @api_client.call_api(:PATCH, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: PathJourneysApi#reactivate_path_journey\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      [data, status_code, headers]
    end

    # Show path journey with provided ID
    # Show path journey with provided ID
    # @param id [String] id
    # @param [Hash] opts the optional parameters
    # @option opts [String] :include Comma-delimited list of sideloaded resources to include as part of the response. See guidance [here](/api/v2/docs#overview--paginating-sideloads) about sideloading large numbers of resources and pagination.  Supported sideloads: signup, path, point_person, current_step_point_person, path_journey_status_change, current_step, path_histories
    # @option opts [String] :fields_path_journeys Comma-delimited list of attributes to only return in the response
    # @return [PathJourneyShowResponse]
    def show_path_journey(id, opts = {})
      data, _status_code, _headers = show_path_journey_with_http_info(id, opts)
      data
    end

    # Show path journey with provided ID
    # Show path journey with provided ID
    # @param id [String] id
    # @param [Hash] opts the optional parameters
    # @option opts [String] :include Comma-delimited list of sideloaded resources to include as part of the response. See guidance [here](/api/v2/docs#overview--paginating-sideloads) about sideloading large numbers of resources and pagination.  Supported sideloads: signup, path, point_person, current_step_point_person, path_journey_status_change, current_step, path_histories
    # @option opts [String] :fields_path_journeys Comma-delimited list of attributes to only return in the response
    # @return [Array<(PathJourneyShowResponse, Integer, Hash)>] PathJourneyShowResponse data, response status code and response headers
    def show_path_journey_with_http_info(id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: PathJourneysApi.show_path_journey ..."
      end
      # verify the required parameter 'id' is set
      if @api_client.config.client_side_validation && id.nil?
        fail ArgumentError, "Missing the required parameter 'id' when calling PathJourneysApi.show_path_journey"
      end
      # resource path
      local_var_path = "/api/v2/path_journeys/{id}".sub("{" + "id" + "}", CGI.escape(id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:include] = opts[:include] if !opts[:include].nil?
      query_params[:"fields[path_journeys]"] = opts[:fields_path_journeys] if !opts[:fields_path_journeys].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"]) unless header_params["Accept"]

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || "PathJourneyShowResponse"

      # auth_names
      auth_names = opts[:debug_auth_names] || ["BearerAuth"]

      new_options = opts.merge(
        operation: :"PathJourneysApi.show_path_journey",
        header_params: header_params,
        query_params: query_params,
        form_params: form_params,
        body: post_body,
        auth_names: auth_names,
        return_type: return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: PathJourneysApi#show_path_journey\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      [data, status_code, headers]
    end

    # Update an existing path journey
    # Updates an existing path journey
    # @param id [String] id
    # @param [Hash] opts the optional parameters
    # @option opts [String] :include Comma-delimited list of sideloaded resources to include as part of the response. See guidance [here](/api/v2/docs#overview--paginating-sideloads) about sideloading large numbers of resources and pagination.  Supported sideloads: signup, path, point_person, current_step_point_person, path_journey_status_change, current_step, path_histories
    # @option opts [String] :fields_path_journeys Comma-delimited list of attributes to only return in the response
    # @option opts [PathJourneyUpdateRequest] :path_journey_update_request
    # @return [PathJourneyShowResponse]
    def update_path_journey(id, opts = {})
      data, _status_code, _headers = update_path_journey_with_http_info(id, opts)
      data
    end

    # Update an existing path journey
    # Updates an existing path journey
    # @param id [String] id
    # @param [Hash] opts the optional parameters
    # @option opts [String] :include Comma-delimited list of sideloaded resources to include as part of the response. See guidance [here](/api/v2/docs#overview--paginating-sideloads) about sideloading large numbers of resources and pagination.  Supported sideloads: signup, path, point_person, current_step_point_person, path_journey_status_change, current_step, path_histories
    # @option opts [String] :fields_path_journeys Comma-delimited list of attributes to only return in the response
    # @option opts [PathJourneyUpdateRequest] :path_journey_update_request
    # @return [Array<(PathJourneyShowResponse, Integer, Hash)>] PathJourneyShowResponse data, response status code and response headers
    def update_path_journey_with_http_info(id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: PathJourneysApi.update_path_journey ..."
      end
      # verify the required parameter 'id' is set
      if @api_client.config.client_side_validation && id.nil?
        fail ArgumentError, "Missing the required parameter 'id' when calling PathJourneysApi.update_path_journey"
      end
      # resource path
      local_var_path = "/api/v2/path_journeys/{id}".sub("{" + "id" + "}", CGI.escape(id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:include] = opts[:include] if !opts[:include].nil?
      query_params[:"fields[path_journeys]"] = opts[:fields_path_journeys] if !opts[:fields_path_journeys].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"]) unless header_params["Accept"]
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(["application/json"])
      if !content_type.nil?
          header_params["Content-Type"] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(opts[:path_journey_update_request])

      # return_type
      return_type = opts[:debug_return_type] || "PathJourneyShowResponse"

      # auth_names
      auth_names = opts[:debug_auth_names] || ["BearerAuth"]

      new_options = opts.merge(
        operation: :"PathJourneysApi.update_path_journey",
        header_params: header_params,
        query_params: query_params,
        form_params: form_params,
        body: post_body,
        auth_names: auth_names,
        return_type: return_type
      )

      data, status_code, headers = @api_client.call_api(:PATCH, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: PathJourneysApi#update_path_journey\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      [data, status_code, headers]
    end

    # Void path journey with provided ID
    # Void path journey with provided ID
    # @param id [String]
    # @param [Hash] opts the optional parameters
    # @option opts [String] :include Comma-delimited list of sideloaded resources to include as part of the response. See guidance [here](/api/v2/docs#overview--paginating-sideloads) about sideloading large numbers of resources and pagination.  Supported sideloads: signup, path, point_person, current_step_point_person, path_journey_status_change, current_step, path_histories
    # @option opts [String] :fields_path_journeys Comma-delimited list of attributes to only return in the response
    # @return [PathJourneyShowResponse]
    def void_path_journey(id, opts = {})
      data, _status_code, _headers = void_path_journey_with_http_info(id, opts)
      data
    end

    # Void path journey with provided ID
    # Void path journey with provided ID
    # @param id [String]
    # @param [Hash] opts the optional parameters
    # @option opts [String] :include Comma-delimited list of sideloaded resources to include as part of the response. See guidance [here](/api/v2/docs#overview--paginating-sideloads) about sideloading large numbers of resources and pagination.  Supported sideloads: signup, path, point_person, current_step_point_person, path_journey_status_change, current_step, path_histories
    # @option opts [String] :fields_path_journeys Comma-delimited list of attributes to only return in the response
    # @return [Array<(PathJourneyShowResponse, Integer, Hash)>] PathJourneyShowResponse data, response status code and response headers
    def void_path_journey_with_http_info(id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: PathJourneysApi.void_path_journey ..."
      end
      # verify the required parameter 'id' is set
      if @api_client.config.client_side_validation && id.nil?
        fail ArgumentError, "Missing the required parameter 'id' when calling PathJourneysApi.void_path_journey"
      end
      # resource path
      local_var_path = "/api/v2/path_journeys/{id}/void".sub("{" + "id" + "}", CGI.escape(id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:include] = opts[:include] if !opts[:include].nil?
      query_params[:"fields[path_journeys]"] = opts[:fields_path_journeys] if !opts[:fields_path_journeys].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"]) unless header_params["Accept"]

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || "PathJourneyShowResponse"

      # auth_names
      auth_names = opts[:debug_auth_names] || ["BearerAuth"]

      new_options = opts.merge(
        operation: :"PathJourneysApi.void_path_journey",
        header_params: header_params,
        query_params: query_params,
        form_params: form_params,
        body: post_body,
        auth_names: auth_names,
        return_type: return_type
      )

      data, status_code, headers = @api_client.call_api(:PATCH, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: PathJourneysApi#void_path_journey\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      [data, status_code, headers]
    end
  end
end
