# #NationBuilder V2 API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 2.0
#
# Generated by: https://openapi-generator.tech
# Generator version: 7.9.0
#

require "cgi"

module NationbuilderClient
  class PetitionSignaturesApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end

    # Create a petition signature
    # Creates a petition signature from given data
    # @param [Hash] opts the optional parameters
    # @option opts [String] :include Comma-delimited list of sideloaded resources to include as part of the response. See guidance [here](/api/v2/docs#overview--paginating-sideloads) about sideloading large numbers of resources and pagination.  Supported sideloads: page, petition, recruiter, signup
    # @option opts [String] :fields_petition_signatures Comma-delimited list of attributes to only return in the response
    # @option opts [PetitionSignatureCreateRequest] :petition_signature_create_request
    # @return [PetitionSignatureShowResponse]
    def create_petition_signature(opts = {})
      data, _status_code, _headers = create_petition_signature_with_http_info(opts)
      data
    end

    # Create a petition signature
    # Creates a petition signature from given data
    # @param [Hash] opts the optional parameters
    # @option opts [String] :include Comma-delimited list of sideloaded resources to include as part of the response. See guidance [here](/api/v2/docs#overview--paginating-sideloads) about sideloading large numbers of resources and pagination.  Supported sideloads: page, petition, recruiter, signup
    # @option opts [String] :fields_petition_signatures Comma-delimited list of attributes to only return in the response
    # @option opts [PetitionSignatureCreateRequest] :petition_signature_create_request
    # @return [Array<(PetitionSignatureShowResponse, Integer, Hash)>] PetitionSignatureShowResponse data, response status code and response headers
    def create_petition_signature_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: PetitionSignaturesApi.create_petition_signature ..."
      end
      # resource path
      local_var_path = "/api/v2/petition_signatures"

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:include] = opts[:include] if !opts[:include].nil?
      query_params[:"fields[petition_signatures]"] = opts[:fields_petition_signatures] if !opts[:fields_petition_signatures].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"]) unless header_params["Accept"]
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(["application/json"])
      if !content_type.nil?
          header_params["Content-Type"] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(opts[:petition_signature_create_request])

      # return_type
      return_type = opts[:debug_return_type] || "PetitionSignatureShowResponse"

      # auth_names
      auth_names = opts[:debug_auth_names] || ["BearerAuth"]

      new_options = opts.merge(
        operation: :"PetitionSignaturesApi.create_petition_signature",
        header_params: header_params,
        query_params: query_params,
        form_params: form_params,
        body: post_body,
        auth_names: auth_names,
        return_type: return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: PetitionSignaturesApi#create_petition_signature\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      [data, status_code, headers]
    end

    # Delete petition signature with provided ID
    # Delete petition signature with provided ID
    # @param id [String] id
    # @param [Hash] opts the optional parameters
    # @option opts [String] :include Comma-delimited list of sideloaded resources to include as part of the response. See guidance [here](/api/v2/docs#overview--paginating-sideloads) about sideloading large numbers of resources and pagination.  Supported sideloads: page, petition, recruiter, signup
    # @option opts [String] :fields_petition_signatures Comma-delimited list of attributes to only return in the response
    # @return [EmptyMetaResponse]
    def delete_petition_signature(id, opts = {})
      data, _status_code, _headers = delete_petition_signature_with_http_info(id, opts)
      data
    end

    # Delete petition signature with provided ID
    # Delete petition signature with provided ID
    # @param id [String] id
    # @param [Hash] opts the optional parameters
    # @option opts [String] :include Comma-delimited list of sideloaded resources to include as part of the response. See guidance [here](/api/v2/docs#overview--paginating-sideloads) about sideloading large numbers of resources and pagination.  Supported sideloads: page, petition, recruiter, signup
    # @option opts [String] :fields_petition_signatures Comma-delimited list of attributes to only return in the response
    # @return [Array<(EmptyMetaResponse, Integer, Hash)>] EmptyMetaResponse data, response status code and response headers
    def delete_petition_signature_with_http_info(id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: PetitionSignaturesApi.delete_petition_signature ..."
      end
      # verify the required parameter 'id' is set
      if @api_client.config.client_side_validation && id.nil?
        fail ArgumentError, "Missing the required parameter 'id' when calling PetitionSignaturesApi.delete_petition_signature"
      end
      # resource path
      local_var_path = "/api/v2/petition_signatures/{id}".sub("{" + "id" + "}", CGI.escape(id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:include] = opts[:include] if !opts[:include].nil?
      query_params[:"fields[petition_signatures]"] = opts[:fields_petition_signatures] if !opts[:fields_petition_signatures].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"]) unless header_params["Accept"]

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || "EmptyMetaResponse"

      # auth_names
      auth_names = opts[:debug_auth_names] || ["BearerAuth"]

      new_options = opts.merge(
        operation: :"PetitionSignaturesApi.delete_petition_signature",
        header_params: header_params,
        query_params: query_params,
        form_params: form_params,
        body: post_body,
        auth_names: auth_names,
        return_type: return_type
      )

      data, status_code, headers = @api_client.call_api(:DELETE, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: PetitionSignaturesApi#delete_petition_signature\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      [data, status_code, headers]
    end

    # List all petition signatures in a nation
    # Lists all petition signatures
    # @param [Hash] opts the optional parameters
    # @option opts [String] :include Comma-delimited list of sideloaded resources to include as part of the response. See guidance [here](/api/v2/docs#overview--paginating-sideloads) about sideloading large numbers of resources and pagination.  Supported sideloads: page, petition, recruiter, signup
    # @option opts [String] :fields_petition_signatures Comma-delimited list of attributes to only return in the response
    # @option opts [String] :page_number Page number to list (starting at 1)
    # @option opts [String] :page_size Number of results to display per page (default: 20, max: 100, min: 1)
    # @return [PetitionSignatureIndexResponse]
    def list_petition_signatures(opts = {})
      data, _status_code, _headers = list_petition_signatures_with_http_info(opts)
      data
    end

    # List all petition signatures in a nation
    # Lists all petition signatures
    # @param [Hash] opts the optional parameters
    # @option opts [String] :include Comma-delimited list of sideloaded resources to include as part of the response. See guidance [here](/api/v2/docs#overview--paginating-sideloads) about sideloading large numbers of resources and pagination.  Supported sideloads: page, petition, recruiter, signup
    # @option opts [String] :fields_petition_signatures Comma-delimited list of attributes to only return in the response
    # @option opts [String] :page_number Page number to list (starting at 1)
    # @option opts [String] :page_size Number of results to display per page (default: 20, max: 100, min: 1)
    # @return [Array<(PetitionSignatureIndexResponse, Integer, Hash)>] PetitionSignatureIndexResponse data, response status code and response headers
    def list_petition_signatures_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: PetitionSignaturesApi.list_petition_signatures ..."
      end
      # resource path
      local_var_path = "/api/v2/petition_signatures"

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:include] = opts[:include] if !opts[:include].nil?
      query_params[:"fields[petition_signatures]"] = opts[:fields_petition_signatures] if !opts[:fields_petition_signatures].nil?
      query_params[:"page[number]"] = opts[:page_number] if !opts[:page_number].nil?
      query_params[:"page[size]"] = opts[:page_size] if !opts[:page_size].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"]) unless header_params["Accept"]

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || "PetitionSignatureIndexResponse"

      # auth_names
      auth_names = opts[:debug_auth_names] || ["BearerAuth"]

      new_options = opts.merge(
        operation: :"PetitionSignaturesApi.list_petition_signatures",
        header_params: header_params,
        query_params: query_params,
        form_params: form_params,
        body: post_body,
        auth_names: auth_names,
        return_type: return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: PetitionSignaturesApi#list_petition_signatures\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      [data, status_code, headers]
    end

    # Show petition signature with provided ID
    # Show petition signature with provided ID
    # @param id [String] id
    # @param [Hash] opts the optional parameters
    # @option opts [String] :include Comma-delimited list of sideloaded resources to include as part of the response. See guidance [here](/api/v2/docs#overview--paginating-sideloads) about sideloading large numbers of resources and pagination.  Supported sideloads: page, petition, recruiter, signup
    # @option opts [String] :fields_petition_signatures Comma-delimited list of attributes to only return in the response
    # @return [PetitionSignatureShowResponse]
    def show_petition_signature(id, opts = {})
      data, _status_code, _headers = show_petition_signature_with_http_info(id, opts)
      data
    end

    # Show petition signature with provided ID
    # Show petition signature with provided ID
    # @param id [String] id
    # @param [Hash] opts the optional parameters
    # @option opts [String] :include Comma-delimited list of sideloaded resources to include as part of the response. See guidance [here](/api/v2/docs#overview--paginating-sideloads) about sideloading large numbers of resources and pagination.  Supported sideloads: page, petition, recruiter, signup
    # @option opts [String] :fields_petition_signatures Comma-delimited list of attributes to only return in the response
    # @return [Array<(PetitionSignatureShowResponse, Integer, Hash)>] PetitionSignatureShowResponse data, response status code and response headers
    def show_petition_signature_with_http_info(id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: PetitionSignaturesApi.show_petition_signature ..."
      end
      # verify the required parameter 'id' is set
      if @api_client.config.client_side_validation && id.nil?
        fail ArgumentError, "Missing the required parameter 'id' when calling PetitionSignaturesApi.show_petition_signature"
      end
      # resource path
      local_var_path = "/api/v2/petition_signatures/{id}".sub("{" + "id" + "}", CGI.escape(id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:include] = opts[:include] if !opts[:include].nil?
      query_params[:"fields[petition_signatures]"] = opts[:fields_petition_signatures] if !opts[:fields_petition_signatures].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"]) unless header_params["Accept"]

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || "PetitionSignatureShowResponse"

      # auth_names
      auth_names = opts[:debug_auth_names] || ["BearerAuth"]

      new_options = opts.merge(
        operation: :"PetitionSignaturesApi.show_petition_signature",
        header_params: header_params,
        query_params: query_params,
        form_params: form_params,
        body: post_body,
        auth_names: auth_names,
        return_type: return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: PetitionSignaturesApi#show_petition_signature\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      [data, status_code, headers]
    end

    # Update an existing petition signature
    # Updates an existing petition signature
    # @param id [String] id
    # @param [Hash] opts the optional parameters
    # @option opts [String] :include Comma-delimited list of sideloaded resources to include as part of the response. See guidance [here](/api/v2/docs#overview--paginating-sideloads) about sideloading large numbers of resources and pagination.  Supported sideloads: page, petition, recruiter, signup
    # @option opts [String] :fields_petition_signatures Comma-delimited list of attributes to only return in the response
    # @option opts [PetitionSignatureUpdateRequest] :petition_signature_update_request
    # @return [PetitionSignatureShowResponse]
    def update_petition_signature(id, opts = {})
      data, _status_code, _headers = update_petition_signature_with_http_info(id, opts)
      data
    end

    # Update an existing petition signature
    # Updates an existing petition signature
    # @param id [String] id
    # @param [Hash] opts the optional parameters
    # @option opts [String] :include Comma-delimited list of sideloaded resources to include as part of the response. See guidance [here](/api/v2/docs#overview--paginating-sideloads) about sideloading large numbers of resources and pagination.  Supported sideloads: page, petition, recruiter, signup
    # @option opts [String] :fields_petition_signatures Comma-delimited list of attributes to only return in the response
    # @option opts [PetitionSignatureUpdateRequest] :petition_signature_update_request
    # @return [Array<(PetitionSignatureShowResponse, Integer, Hash)>] PetitionSignatureShowResponse data, response status code and response headers
    def update_petition_signature_with_http_info(id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: PetitionSignaturesApi.update_petition_signature ..."
      end
      # verify the required parameter 'id' is set
      if @api_client.config.client_side_validation && id.nil?
        fail ArgumentError, "Missing the required parameter 'id' when calling PetitionSignaturesApi.update_petition_signature"
      end
      # resource path
      local_var_path = "/api/v2/petition_signatures/{id}".sub("{" + "id" + "}", CGI.escape(id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:include] = opts[:include] if !opts[:include].nil?
      query_params[:"fields[petition_signatures]"] = opts[:fields_petition_signatures] if !opts[:fields_petition_signatures].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["application/json"]) unless header_params["Accept"]
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(["application/json"])
      if !content_type.nil?
          header_params["Content-Type"] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(opts[:petition_signature_update_request])

      # return_type
      return_type = opts[:debug_return_type] || "PetitionSignatureShowResponse"

      # auth_names
      auth_names = opts[:debug_auth_names] || ["BearerAuth"]

      new_options = opts.merge(
        operation: :"PetitionSignaturesApi.update_petition_signature",
        header_params: header_params,
        query_params: query_params,
        form_params: form_params,
        body: post_body,
        auth_names: auth_names,
        return_type: return_type
      )

      data, status_code, headers = @api_client.call_api(:PATCH, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: PetitionSignaturesApi#update_petition_signature\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      [data, status_code, headers]
    end
  end
end
